module.exports = [
	{ field: "Name", type: "String", desc: "" },
	{ field: "Title", type: "String", desc: "" },
	{ field: "ReleaseDate", type: "Date", desc: "" },
	{ field: "BE", type: "Integer", desc: "" },
	{ field: "RP", type: "Integer", desc: "" },
	{ field: "Attributes", type: "List (,) of String", desc: "" },
	{ field: "Resource", type: "String", desc: "" },
	{ field: "RealName", type: "String", desc: "" },
	{ field: "Health", type: "Float", desc: "" },
	{ field: "HPLevel", type: "Float", desc: "" },
	{ field: "HPDisplay", type: "Wikitext", desc: "" },
	{ field: "HPLevelDisplay", type: "Wikitext", desc: "" },
	{ field: "HPRegen", type: "Float", desc: "" },
	{ field: "HPRegenLevel", type: "Float", desc: "" },
	{ field: "Mana", type: "Float", desc: "" },
	{ field: "ManaLevel", type: "Float", desc: "" },
	{ field: "ManaRegen", type: "Float", desc: "" },
	{ field: "ManaRegenLevel", type: "Float", desc: "" },
	{ field: "Energy", type: "Float", desc: "" },
	{ field: "EnergyRegen", type: "Float", desc: "" },
	{ field: "Movespeed", type: "Float", desc: "" },
	{ field: "AttackDamage", type: "Float", desc: "" },
	{ field: "ADLevel", type: "Float", desc: "" },
	{ field: "AttackSpeed", type: "Float", desc: "" },
	{ field: "ASLevel", type: "Float", desc: "" },
	{ field: "AttackRange", type: "Float", desc: "" },
	{ field: "Armor", type: "Float", desc: "" },
	{ field: "ArmorLevel", type: "Float", desc: "" },
	{ field: "MagicResist", type: "Float", desc: "" },
	{ field: "MagicResistLevel", type: "Float", desc: "" },
	{ field: "Pronoun", type: "String", desc: "Gender pronoun" },
	{ field: "KeyDdragon", type: "String", desc: "Riot's Data-Dragon json key" },
	{ field: "KeyInteger", type: "Integer", desc: "Integer key used in Riot data" },
]
