module.exports = [
	{ field: "Year", type: "Integer", desc: "" },
	{ field: "Champion", type: "String", desc: "" },
	{ field: "ChampionRange", type: "String", desc: "" },
	{ field: "DamageType", type: "String", desc: "" },
	{ field: "CCLevel", type: "Integer", desc: "" },
	{ field: "BurstLevel", type: "Integer", desc: "" },
	{ field: "SustainedLevel", type: "Integer", desc: "" },
	{ field: "TankLevel", type: "Integer", desc: "" },
	{ field: "Goal", type: "String", desc: "" },
	{ field: "Strengths", type: "String", desc: "" },
	{ field: "Weaknesses", type: "String", desc: "" },
	{ field: "Ultimate", type: "String", desc: "" },
	{ field: "Mechanic", type: "String", desc: "" },
	{ field: "Classes", type: "List (,) of String", desc: "" },
	{ field: "Roles", type: "List (,) of String", desc: "" },
]
