module.exports = [
	{ field: "Title", type: "String", desc: "" },
	{ field: "URL", type: "Text", desc: "" },
	{ field: "ContentType", type: "String ", desc: "Announcement, Interview, Article" },
	{ field: "MediaType", type: "String ", desc: "Viedeo, Written" },
	{ field: "Language", type: "String", desc: "" },
	{ field: "Players", type: "List (,) of String", desc: "" },
	{ field: "Tournaments", type: "List (,) of String", desc: "" },
	{ field: "Teams", type: "List (,) of String", desc: "" },
	{ field: "Date", type: "DateTime", desc: "" },
	{ field: "Year", type: "Integer", desc: "" },
	{ field: "Publication", type: "String", desc: "" },
	{ field: "N_ItemInDate", type: "Integer", desc: "" },
	{ field: "Authors", type: "List (,) of String", desc: "" },
	{ field: "Translators", type: "String", desc: "" },
	{ field: "Series", type: "String", desc: "name of the recurring content series if applicable" },
	{ field: "SeriesSeason", type: "String", desc: 'name of the season (e.g. "season 1") of the recurring content series if applicable' },
	{ field: "SeriesSeasonNumber", type: "Integer", desc: "sort number (e.g. 1) of the season of the recurring content series if applicable" },
]
