module.exports = [
	{ field: "Name", type: "String", desc: "" },
	{ field: "Recipe", type: "List (+) of String", desc: "" },
	{ field: "Cost", type: "Integer", desc: "" },
	{ field: "TotalCost", type: "Integer", desc: "" },
	{ field: "AD", type: "Integer", desc: "" },
	{ field: "LifeSteal", type: "Integer", desc: "" },
	{ field: "Health", type: "Integer", desc: "" },
	{ field: "HPRegen", type: "Integer", desc: "" },
	{ field: "Armor", type: "Integer", desc: "" },
	{ field: "MR", type: "Integer", desc: "" },
	{ field: "AttackDamage", type: "Integer", desc: "" },
	{ field: "Crit", type: "Integer", desc: "" },
	{ field: "AttackSpeed", type: "Integer", desc: "" },
	{ field: "LifeSteal", type: "Integer", desc: "" },
	{ field: "ArPen", type: "Integer", desc: "" },
	{ field: "AttackRange", type: "Integer", desc: "" },
	{ field: "Mana", type: "Integer", desc: "" },
	{ field: "ManaRegen", type: "Integer", desc: "" },
	{ field: "Energy", type: "Integer", desc: "" },
	{ field: "EnergyRegen", type: "Integer", desc: "" },
	{ field: "AP", type: "Integer", desc: "" },
	{ field: "CDR", type: "Integer", desc: "" },
	{ field: "SpellVamp", type: "Integer", desc: "" },
	{ field: "MPen", type: "Integer", desc: "" },
	{ field: "Movespeed", type: "Integer", desc: "" },
	{ field: "Tenacity", type: "Integer", desc: "" },
	{ field: "GoldGen", type: "Integer", desc: "" },
	{ field: "OnHit", type: "Integer", desc: "" },
	{ field: "BonusHP", type: "Integer", desc: "" },
	{ field: "Healing", type: "Integer", desc: "" },
]
