module.exports = [
	{ field: "ID", type: "String", desc: "" },
	{ field: "ID_Linked", type: "Wikitext", desc: "" },
	{ field: "Link", type: "String", desc: "" },
	{ field: "Name", type: "String", desc: "" },
	{ field: "N", type: "Integer", desc: "" },
	{ field: "Country", type: "String", desc: "" },
	{ field: "Country_Markup", type: "Wikitext", desc: "" },
	{ field: "Role", type: "String", desc: "" },
	{ field: "RoleFull", type: "String", desc: "" },
	{ field: "IsSubstitute", type: "String", desc: "" },
	{ field: "IsTrainee", type: "String", desc: "" },
	{ field: "PlayerNo", type: "Integer", desc: "" },
	{ field: "Team", type: "String", desc: "" },
	{ field: "Team_Markup", type: "Wikitext", desc: "" },
	{ field: "ContractDate", type: "Date", desc: "" },
	{ field: "Residency", type: "String", desc: "" },
	{ field: "Residency_Image", type: "Wikitext", desc: "" },
	{ field: "Residency_Markup", type: "Wikitext", desc: "" },
	{ field: "PlayerListLine", type: "Wikitext", desc: "" },
]
