module.exports = [
	{ field: "Display", type: "String", desc: "" },
	{ field: "Link", type: "String", desc: "" },
	{ field: "Year", type: "String", desc: "Season" },
	{ field: "Cycle1", type: "Integer", desc: "" },
	{ field: "Cycle2", type: "Integer", desc: "" },
	{ field: "Cycle3", type: "Integer", desc: "" },
	{ field: "Cycle4", type: "Integer", desc: "" },
	{ field: "Cycle5", type: "Integer", desc: "" },
	{ field: "Cycle6", type: "Integer", desc: "" },
	{ field: "Cycle7", type: "Integer", desc: "" },
	{ field: "Cycle8", type: "Integer", desc: "" },
	{ field: "Total", type: "Integer", desc: "" },
	{ field: "Role", type: "String", desc: "" },
]
