module.exports = [
	{ field: "Date_Display", type: "String", desc: "Date for displaying in timelines, may contain \"approx\" etc" },
	{ field: "Date_Sort", type: "DateTime", desc: "Invisible to the reader, but must be an exact date. Can guess if the date is approximate, put qualifying information into Date_Display" },
	{ field: "IsApproxDate", type: "Boolean", desc: "If the date is approx or not - independent from how much precision to use as the display, this will just add the text (approx.)" },
	{ field: "EarliestPossibleDate", type: "Date", desc: "Based on values of approx/display date" },
	{ field: "LatestPossibleDate", type: "Date", desc: "Based on values of approx/display date" },
	{ field: "Sentence", type: "Wikitext", desc: "Display text (English-only)" },
	{ field: "SentenceWithDate", type: "Wikitext", desc: "Display text (English-only). Prefixed by display date." },
	{ field: "Sentence_Team", type: "Wikitext", desc: "Display text specifically for team page(s) (English-only)" },
	{ field: "Sentence_Player", type: "Wikitext", desc: "Display text specifically for player page(s) (English-only)" },
	{ field: "Sentence_Tournament", type: "Wikitext", desc: "Display text specifically for tournament page(s) (English-only)" },
	{ field: 'Subject', type: 'String', desc: "Subject to show in subject column if applicable" },
	{ field: 'SubjectType', type: "String", desc: "Team, Tournament" },
	{ field: 'SubjectLink', type: "String", desc: "Link if different from subject" },
	{ field: "Preload", type: "String", desc: "Unification of any preload type, including but not limited to move_type from RosterChangeData" },
	{ field: "Region", type: "String", desc: "" },
	{ field: "Players", type: "List (,) of String", desc: "Players (or support staff, etc; people) involved in this news" },
	{ field: "Teams", type: "List (,) of String", desc: "Teams involved in this news" },
	{ field: "Tournaments", type: "List (,) of String", desc: "Tournaments involved in this news" },
	{ field: "Tags", type: "List (,) of String", desc: "Tags if needed, though probably don't duplicate RosterChanges tags here" },
	{ field: "Source", type: "Wikitext", desc: "source for the change" },
	{ field: "N_LineInDate", type: "Integer", desc: "For sorting news on a single day" },
	{ field: "NewsId", type: "String", desc: "For joining all types of news together" },
	{ field: "ExcludeFrontpage", type: "Boolean", desc: "Don't include this line in the wiki's front page news (because it's not notable enough)" },
	{ field: "ExcludePortal", type: "Boolean", desc: "Don't include this line on roster change portals (anything with ExcludeFrontpage=true will also be excluded from portals)" },
]
