module.exports = [
	{ field: "N", type: "Integer", desc: "" },
	{ field: "DateDisplay", type: "String", desc: "" },
	{ field: "DateSort", type: "Date", desc: "" },
	{ field: "Region", type: "String", desc: "" },
	{ field: "Tournament", type: "String", desc: "" },
	{ field: "OverviewPage", type: "String", desc: "" },
	{ field: "Team", type: "String", desc: "" },
	{ field: "TeamVs", type: "String", desc: "" },
	{ field: "Name", type: "String", desc: "" },
	{ field: "Link", type: "String", desc: "" },
	{ field: "Champion", type: "String", desc: "" },
	{ field: "Role", type: "String", desc: "" },
	{ field: "Win", type: "Boolean", desc: "" },
	{ field: "Kills", type: "Integer", desc: "" },
	{ field: "Deaths", type: "Integer", desc: "" },
	{ field: "Assists", type: "Integer", desc: "" },
	{ field: "ScoreboardLink", type: "String", desc: "" },
	{ field: "Vod", type: "String", desc: "" },
]
