module.exports = [
	{ field: "Team1Role1 ", type: " String", desc: "Role of the first-picked blue-side champion" },
	{ field: "Team1Role2 ", type: " String", desc: "Role of the second-picked blue-side champion" },
	{ field: "Team1Role3 ", type: " String", desc: "Role of the third-picked blue-side champion" },
	{ field: "Team1Role4 ", type: " String", desc: "Role of the fourth-picked blue-side champion" },
	{ field: "Team1Role5 ", type: " String", desc: "Role of the fifth-picked blue-side champion" },
	{ field: "Team2Role1 ", type: " String", desc: "Role of the first-picked red-side champion" },
	{ field: "Team2Role2 ", type: " String", desc: "Role of the second-picked red-side champion" },
	{ field: "Team2Role3 ", type: " String", desc: "Role of the third-picked red-side champion" },
	{ field: "Team2Role4 ", type: " String", desc: "Role of the fourth-picked red-side champion" },
	{ field: "Team2Role5 ", type: " String", desc: "Role of the fifth-picked red-side champion" },
	{ field: "Team1Ban1 ", type: " String", desc: "" },
	{ field: "Team1Ban2 ", type: " String", desc: "" },
	{ field: "Team1Ban3 ", type: " String", desc: "" },
	{ field: "Team1Ban4 ", type: " String", desc: "" },
	{ field: "Team1Ban5 ", type: " String", desc: "" },
	{ field: "Team1Pick1 ", type: " String", desc: "" },
	{ field: "Team1Pick2 ", type: " String", desc: "" },
	{ field: "Team1Pick3 ", type: " String", desc: "" },
	{ field: "Team1Pick4 ", type: " String", desc: "" },
	{ field: "Team1Pick5 ", type: " String", desc: "" },
	{ field: "Team2Ban1 ", type: " String", desc: "" },
	{ field: "Team2Ban2 ", type: " String", desc: "" },
	{ field: "Team2Ban3 ", type: " String", desc: "" },
	{ field: "Team2Ban4 ", type: " String", desc: "" },
	{ field: "Team2Ban5 ", type: " String", desc: "" },
	{ field: "Team2Pick1 ", type: " String", desc: "" },
	{ field: "Team2Pick2 ", type: " String", desc: "" },
	{ field: "Team2Pick3 ", type: " String", desc: "" },
	{ field: "Team2Pick4 ", type: " String", desc: "" },
	{ field: "Team2Pick5 ", type: " String", desc: "" },
	{ field: "Team1 ", type: " String", desc: "" },
	{ field: "Team2 ", type: " String", desc: "" },
	{ field: "Winner ", type: " Integer", desc: "" },
	{ field: "Team1Score ", type: " Integer", desc: "" },
	{ field: "Team2Score ", type: " Integer", desc: "" },
	{ field: "Team1PicksByRoleOrder", type: "String", desc: "string of picks by role order for comparing with ScoreboardGames" },
	{ field: "Team2PicksByRoleOrder", type: "String", desc: "string of picks by role order for comparing with ScoreboardGames" },
	{ field: "OverviewPage ", type: " String", desc: "" },
	{ field: "Phase ", type: " String", desc: "" },
	{ field: "UniqueLine ", type: " String", desc: "" },
	{ field: "IsComplete", type: "Boolean", desc: "" },
	{ field: "Tab ", type: " String", desc: "Name of the tab (h2 heading on a pick-ban page, corresponds to a tab in MatchSchedule as well)" },
	{ field: "N_Page ", type: " Integer ", desc: "N of page within pick-ban section for event" },
	{ field: "N_TabInPage ", type: " Integer", desc: "" },
	{ field: "N_MatchInPage ", type: " Integer", desc: "" },
	{ field: "N_GameInPage ", type: " Integer", desc: "" },
	{ field: "N_GameInMatch ", type: " Integer", desc: "" },
	{ field: "N_MatchInTab ", type: " Integer", desc: "" },
	{ field: "N_GameInTab ", type: " Integer", desc: "" },
	{ field: "GameID_Wiki", type: "String", desc: "OverviewPage_Tab_MatchInTab_GameInMatch" },
]
