module.exports = [
	{ field: "ID", type: "String", desc: "Player's current IGN" },
	{ field: "OverviewPage", type: "String", desc: "alias for _pageName, use this instead" },
	{ field: "Player", type: "String", desc: "Case-sensitive version of OverviewPage" },
	{ field: "Image", type: "String", desc: "File name of the player's image on the wiki, not prefixed by \"File:\". Able to be joined to _pageData._pageTitle." },
	{ field: "Name", type: "String", desc: "IRL name of the player" },
	{ field: "NativeName", type: "String", desc: "IRL name of the player, not transliterated to English characters, nil if the player's name is already in English characters" },
	{ field: "NameAlphabet", type: "String", desc: "Alphabet used in NativeName field, if applicable" },
	{ field: "NameFull", type: "String", desc: "Transliterated name alongside native name, if native name is defined; this field can be derived from Name and NativeName but exists for convenience" },
	{ field: "Country", type: "String", desc: "Country of birth" },
	{ field: "Nationality", type: "List (,) of String", desc: "Country of nationality" },
	{ field: "NationalityPrimary", type: "String", desc: "Only the first country of nationality" },
	{ field: "Age", type: "Integer", desc: "Player's age" },
	{ field: "Birthdate", type: "Date", desc: "Player's birthday" },
	{ field: "ResidencyFormer", type: "String", desc: "Previous Riot-official residency the player has held, if any" },
	{ field: "Team", type: "String", desc: "Current team" },
	{ field: "Team2", type: "String", desc: "Second team, if any - more than 2 teams may be displayed but only two are stored" },
	{ field: "CurrentTeams", type: "List (,) of String", desc: "List of all current teams" },
	{ field: "TeamSystem", type: "String", desc: "Team 1 System (PC/XBox/etc) - may not apply to individual wikis but added to all for consistency" },
	{ field: "Team2System", type: "String", desc: "Team 2 System (PC/XBox/etc) - may not apply to individual wikis but added to all for consistency" },
	{ field: "Residency", type: "String", desc: "Official Riot residency" },
	{ field: "Role", type: "String", desc: "Player's primary role" },
	{ field: "FavChamps", type: "List (,) of String", desc: "Favorite champions - this value is filled manually and may have nothing to do with performance" },
	{ field: "SoloqueueIds", type: "Text", desc: "List of soloqueue IDs, this is manually maintained and may be extremely incomplete or inaccurate" },
	{ field: "Stream", type: "String", desc: "Player's Stream (full URL)" },
	{ field: "Twitter", type: "String", desc: "Player's Twitter ID (username only)" },
	{ field: "Facebook", type: "String", desc: "Player's Facebook (full URL)" },
	{ field: "Askfm", type: "String", desc: "Player's AskFM (username only)" },
	{ field: "Reddit", type: "String", desc: "Player's reddit (Username only)" },
	{ field: "Youtube", type: "String", desc: "Player's YouTube (full URL)" },
	{ field: "Weibo", type: "String", desc: "Player's Weibo (full URL)" },
	{ field: "Vk", type: "String", desc: "Player's VKontakte (full URL)" },
	{ field: "Instagram", type: "String", desc: "Player's Instagram (Username only)" },
	{ field: "TeamLast", type: "String", desc: "Last team the player played on, may be same as current team" },
	{ field: "RoleLast", type: "String", desc: "Last role the player had, may be same as current role" },
	{ field: "IsRetired", type: "Boolean", desc: "Is the player retired?" },
	{ field: "IsPersonality", type: "Boolean", desc: "Is this a page about a personality rather than a player?" },
	{ field: "IsSubstitute", type: "Boolean", desc: "Is the player a substitute on their current team?" },
	{ field: 'IsTrainee', type: 'Boolean', desc: 'Is the player a trainee on their current team?' },
	{ field: "IsLowercase", type: "Boolean", desc: "Should the title of this page be lowercased?" },
	{ field: "IsAutoTeam", type: "Boolean", desc: "Is the team auto generated from roster portal?" },
	{ field: "IsLowContent", type: "Boolean", desc: "Is this a low-content page? For internal use only." },
]
