module.exports = [
	{ field: "Date", type: "Date", desc: "Date the rumor was published" },
	{ field: "Status", type: "String", desc: "" },
	{ field: "IsOver", type: "Boolean", desc: "Does the status resolve the state of the rumor?" },
	{ field: "NotHappening", type: "Boolean", desc: "Is the rumor that this thing ISN'T happening?" },
	{ field: "Player", type: "String", desc: "Player rumor is about" },
	{ field: "Regions", type: "List (,) of String", desc: "Both regions included in the change, if applicable" },
	{ field: "TeamStart", type: "String", desc: "Starting team" },
	{ field: "TeamEnd", type: "String", desc: "Ending team" },
	{ field: "LeagueStart", type: "String", desc: "Should not be declared alongside TeamStart" },
	{ field: "LeagueEnd", type: "String", desc: "Should not be declared alongside a TeamEnd" },
	{ field: "RegionStart", type: "String", desc: "" },
	{ field: "RegionEnd", type: "String", desc: "" },
	{ field: "RoleStart", type: "String", desc: "" },
	{ field: "RoleEnd", type: "String", desc: "" },
	{ field: "IsSubStart", type: "Boolean", desc: "" },
	{ field: "IsSubEnd", type: "Boolean", desc: "" },
	{ field: "IsTraineeStart", type: "Boolean", desc: "" },
	{ field: "IsTraineeEnd", type: "Boolean", desc: "" },
	{ field: "CustomText", type: "Wikitext", desc: "" },
	{ field: "SourceLink", type: "Text", desc: "" },
	{ field: "SourceAuthors", type: "List (,) of String", desc: "" },
	{ field: "SourceSite", type: "String", desc: "ESPN, Twitter, etc" },
	{ field: "StatusLink", type: "Text", desc: "" },
	{ field: "N_LineInDate", type: "Integer", desc: "" },
]
