module.exports = [
	{ field: 'Team', type: 'String', desc: 'Link of the team' },
	{ field: 'Side', type: 'String', desc: 'Blue or Red' },
	{ field: 'Number', type: 'Integer', desc: '1 or 2' },
	{ field: 'IsWinner', type: 'Boolean', desc: '' },
	{ field: 'Score', type: 'Integer', desc: 'Cumulative in series' },
	{ field: 'Bans', type: 'List (,) of String', desc: '' },
	{ field: 'Picks', type: 'List (,) of String', desc: '' },
	{ field: 'Roster', type: 'List (,) of String', desc: 'Links' },
	{ field: 'Dragons', type: 'Integer', desc: 'Total dragons+drakes+elder' },
	{ field: 'Barons', type: 'Integer', desc: '' },
	{ field: 'Towers', type: 'Integer', desc: '' },
	{ field: 'Gold', type: 'Integer', desc: '' },
	{ field: 'Kills', type: 'Integer', desc: '' },
	{ field: 'RiftHeralds', type: 'Integer', desc: '' },
	{ field: 'Inhibitors', type: 'Integer', desc: '' },
	{ field: 'OverviewPage', type: "String", desc: "" },
	{ field: 'StatsPage', type: 'String', desc: "For internal use, the name of the team's year stats page" },
	{ field: 'UniqueGame', type: 'String', desc: 'Join to ScoreboardGames, ScoreboardTeams' },
	{ field: 'UniqueTeam', type: 'String', desc: 'Primary key' },
]
