module.exports = [
	{ field: "Tournament", type: "String", desc: "" },
	{ field: "Team1", type: "String", desc: "" },
	{ field: "Team2", type: "String", desc: "" },
	{ field: "WinTeam", type: "String", desc: "Team name of winner" },
	{ field: "LossTeam", type: "String", desc: "Team name of loser" },
	{ field: "DateTime_UTC ", type: "Datetime", desc: "" },
	{ field: "DST", type: "String", desc: "yes/no/spring/fall" },
	{ field: "Team1Score", type: "Integer", desc: "" },
	{ field: "Team2Score", type: "Integer", desc: "" },
	{ field: "Winner", type: "Integer", desc: "1 or 2" },
	{ field: "Gamelength", type: "String", desc: "Game length in format H:MM:SS or MM:SS" },
	{ field: "Gamelength_Number", type: "Float", desc: "Number of minutes that the game lasted" },
	{ field: "Team1Bans", type: "List (,) of String", desc: "" },
	{ field: "Team2Bans", type: "List (,) of String", desc: "" },
	{ field: "Team1Picks", type: "List (,) of String", desc: "" },
	{ field: "Team2Picks", type: "List (,) of String", desc: "" },

	{ field: "Team1Names", type: "List (,) of String", desc: "Player roster display names" },
	{ field: "Team2Names", type: "List (,) of String", desc: "Player roster display names" },
	{ field: "Team1Links", type: "List (,) of String", desc: "Player roster page links" },
	{ field: "Team2Links", type: "List (,) of String", desc: "Player roster page links" },

	{ field: "Team1Dragons", type: "Integer", desc: "" },
	{ field: "Team2Dragons", type: "Integer", desc: "" },
	{ field: "Team1Barons", type: "Integer", desc: "" },
	{ field: "Team2Barons", type: "Integer", desc: "" },
	{ field: "Team1Towers", type: "Integer", desc: "" },
	{ field: "Team2Towers", type: "Integer", desc: "" },
	{ field: "Team1Gold", type: "Float", desc: "" },
	{ field: "Team2Gold", type: "Float", desc: "" },
	{ field: "Team1Kills", type: "Integer", desc: "" },
	{ field: "Team2Kills", type: "Integer", desc: "" },
	{ field: "Team1RiftHeralds", type: "Integer", desc: "" },
	{ field: "Team2RiftHeralds", type: "Integer", desc: "" },
	{ field: "Team1Inhibitors", type: "Integer", desc: "" },
	{ field: "Team2Inhibitors", type: "Integer", desc: "" },

	{ field: "Patch", type: "String", desc: "" },
	{ field: "MatchHistory", type: "String", desc: "Riot or QQ match history for the game" },
	{ field: "VOD", type: "String", desc: "Generally the timestamp will be pick-ban start" },

	{ field: "N_Page", type: "Integer", desc: "" },
	{ field: "N_MatchInTab", type: "Integer", desc: "" },
	{ field: "N_MatchInPage", type: "Integer", desc: "" },
	{ field: "N_GameInMatch", type: "Integer", desc: "" },
	{ field: "Gamename", type: "String", desc: "" },
	{ field: "OverviewPage ", type: " String", desc: "" },
	{ field: "UniqueGame", type: "String", desc: "Join to ScoreboardGames, ScoreboardTeams" },
	{ field: "UniqueLine", type: "String", desc: "" },
	{ field: "ScoreboardID_Wiki", type: "String", desc: "" },
	{ field: "ScoreboardID_Riot", type: "String", desc: "" },

	{ field: "Note1", type: "String", desc: "" },
	{ field: "Note2", type: "String", desc: "" },
	{ field: "Note3", type: "String", desc: "" },
	{ field: "Note4", type: "String", desc: "" },
]
