module.exports = [
	{ field: "Event", type: "String", desc: "" },
	{ field: "Tier", type: "String", desc: "" },
	{ field: "Date", type: "Date", desc: "May be earlier than the end date of the tournament if the player was eliminated early" },
	{ field: "Place", type: "String", desc: "" },
	{ field: "Prize", type: "Integer", desc: "" },
	{ field: "Prize_USD", type: "Float", desc: "" },
	{ field: "Prize_Euro", type: "Float", desc: "" },
	{ field: "PrizeUnit", type: "String", desc: "" },
	{ field: "Prize_Markup", type: "String", desc: "" },
	{ field: "PrizeOther", type: "String", desc: "" },
	{ field: "Phase", type: "String", desc: "" },
	{ field: "Player", type: "String", desc: "" },
	{ field: "PlayerLink", type: "String", desc: "" },
	{ field: "Team", type: "String", desc: "" },
	{ field: "LastResult", type: "String", desc: "" },
	{ field: "LastOpponent", type: "String", desc: "" },
	{ field: "LastOpponentLink", type: "String", desc: "" },
	{ field: "LastOutcome", type: "String", desc: "" },
	{ field: "LastOpponentTeam", type: "String", desc: "" },
	{ field: "OverviewPage", type: "String", desc: "" },
	{ field: "UniqueLine", type: "String (size=200)", desc: "" },
]
