module.exports = [
	{ field: "Name", type: "String", desc: "" },
	{ field: "DateStart", type: "Date", desc: "" },
	{ field: "Date", type: "Date", desc: "" },
	{ field: "League", type: "String", desc: "" },
	{ field: "Region", type: "String", desc: "" },
	{ field: "Prizepool", type: "String", desc: "" },
	{ field: "Currency", type: "String", desc: "" },

	{ field: "Country", type: "String", desc: "" },
	{ field: "ClosestTimezone", type: "String", desc: "allowed values: PST, KST, CET" },
	{ field: "Rulebook", type: "String", desc: "" },
	{ field: "EventType", type: "String", desc: "" },
	{ field: "Links", type: "String", desc: "" },
	{ field: "Sponsors", type: "String", desc: "" },
	{ field: "Organizer", type: "String", desc: "" },
	{ field: "Organizers", type: "List (,) of String", desc: "" },

	{ field: "StandardName", type: "String", desc: "" },
	{ field: "StandardName_Redirect", type: "String", desc: "Redirect-friendly version of StandardName, with certain characters removed such as '#'" },
	{ field: "Split", type: "String", desc: "" },
	{ field: "SplitNumber", type: "Integer", desc: "" },
	{ field: "TournamentLevel", type: "String", desc: "" },
	{ field: "IsQualifier", type: "Boolean", desc: "" },
	{ field: "IsPlayoffs", type: "Boolean", desc: "" },
	{ field: "IsOfficial", type: "Boolean", desc: "" },
	{ field: "Year", type: "String", desc: "" },
	{ field: "StandardLeague", type: "String", desc: "" },
	{ field: "LeagueIconKey", type: "String", desc: "" },

	{ field: "Tags", type: "List (,) of String", desc: "" },

	{ field: "OverviewPage", type: "String", desc: "" },
	{ field: "SuppressTopSchedule", type: "Boolean", desc: "For internal use, to hide matches from top schedule" },
]
