module.exports = [
	{ field: "Event", type: "String", desc: "" },
	{ field: "Tier", type: "String", desc: "" },
	{ field: "Date", type: "Date", desc: "Note this may be different from event date if the team was eliminated on an earlier date than the finals" },
	{ field: "RosterPage", type: "Page", desc: "" },
	{ field: "Place", type: "String", desc: "" },
	{ field: "ForceNewPlace", type: "Boolean", desc: "" },
	{ field: "Place_Number", type: "Integer", desc: "A sortable number equal to the top place in the range of places, if place is a range (e.g. 3-4 will have 3 here)" },
	{ field: "Qualified", type: "Boolean", desc: "A fallback to show qualified teams if there was both qualification & place" },
	{ field: "Prize", type: "Integer", desc: "" },
	{ field: "Prize_USD", type: "Float", desc: "" },
	{ field: "Prize_Euro", type: "Float", desc: "" },
	{ field: "PrizeUnit", type: "String", desc: "" },
	{ field: "Prize_Markup", type: "String", desc: "" },
	{ field: "PrizeOther", type: "String", desc: "" },
	{ field: "Phase", type: "String", desc: "" },
	{ field: "Team", type: "String", desc: "" },
	{ field: "IsAchievement", type: "Boolean", desc: "True for the results that are above the show/hide more results line" },
	{ field: "LastResult", type: "String", desc: "Score" },
	{ field: "LastTeam", type: "String", desc: "Last team played against, bracket play only" },
	{ field: "LastOpponent_Markup", type: "Wikitext", desc: "This is anything, and will probably be the display in Team Results module. Always defined, either with a team or a group stage record." },
	{ field: "GroupName", type: "String", desc: [[This will be undefined if it's not a group, otherwise it will default to "Group Stage" or whatever the name of the group is given.]] },
	{ field: "LastOutcome", type: "String", desc: "Win or Loss, applies to bracket play only" },
	{ field: "PageAndTeam", type: "String", desc: "" },
	{ field: "OverviewPage", type: "String", desc: "" },
	{ field: "UniqueLine", type: "String (size=200)", desc: "" },
]
