export type Field<T extends Table> = FieldMap[T][number]

type UnderscoreToSpace<S> = S extends `${infer L}_${infer R}`
  ? L extends ''
    ? S
    : `${L} ${R}`
  : S
type ToFieldName<Field> = Field extends `${Table}.${infer FieldName}`
  ? UnderscoreToSpace<FieldName>
  : never

export type Item<Field> = {
  [key in ToFieldName<Field>]: any
}

export type JoinOn<
  T extends Table,
  LeftField extends Field<T>,
  // infer left table with template literal type
> = LeftField extends `${infer LeftTable}.${string}`
  ? {
      // use type argument inference
      left: LeftField
      right: Field<Exclude<T, LeftTable>>
    }
  : never

export interface OrderBy<T extends Table> {
  field: Field<T>
  desc?: boolean
}

export interface Parameter<T extends Table, LeftField extends Field<T>> {
  tables: T[]
  fields?: Field<T>[]
  where?: string
  joinOn?: JoinOn<T, LeftField>[]
  groupBy?: Field<T>[]
  having?: string
  orderBy?: OrderBy<T>[]
  limit?: number
  offset?: number
  format?: string
}

export type Table =
  | 'Alphabets'
  | 'BroadcastMusicTrackTypes'
  | 'BroadcastMusicTracks'
  | 'BroadcastMusicUsages'
  | 'CargoAttachments'
  | 'ChampionFlashcards'
  | 'Champions'
  | 'ChromaSets'
  | 'Chromas'
  | 'Contracts'
  | 'CurrentLeagues'
  | 'Disambiguations'
  | 'Entities'
  | 'ExternalContent'
  | 'GCDArchive'
  | 'Hooks'
  | 'IgnorePagedata'
  | 'IndividualAchievements'
  | 'Items'
  | 'LeagueGroups'
  | 'Leagues'
  | 'ListplayerCurrent'
  | 'LowPriorityRedirects'
  | 'MatchSchedule'
  | 'MatchScheduleGame'
  | 'NASGLadder2018'
  | 'NASGLadder7Cycles'
  | 'NTLGlossary'
  | 'NewsItems'
  | 'Organizations'
  | 'ParticipantsArgs'
  | 'PatchNotes'
  | 'Pentakills'
  | 'PicksAndBansS7'
  | 'PlayerImages'
  | 'PlayerLeagueHistory'
  | 'PlayerPronunciationFiles'
  | 'PlayerRedirects'
  | 'PlayerRenames'
  | 'Players'
  | 'RegionStatuses'
  | 'Regions'
  | 'ResidencyChanges'
  | 'Retirements'
  | 'RosterChangePortalDates'
  | 'RosterChangePortalPages'
  | 'RosterChanges'
  | 'RosterRumors'
  | 'ScoreboardGames'
  | 'ScoreboardPlayers'
  | 'ScoreboardTeams'
  | 'SisterTeams'
  | 'Skins'
  | 'SkinsUsed'
  | 'Standings'
  | 'StandingsArgs'
  | 'TeamRedirects'
  | 'TeamRenames'
  | 'TeamRosterPhotos'
  | 'Teams'
  | 'TeamsWithAutoRosters'
  | 'Tenures'
  | 'TenuresUnbroken'
  | 'TournamentGroups'
  | 'TournamentPlayers'
  | 'TournamentResults'
  | 'TournamentResults1v1'
  | 'TournamentRosters'
  | 'TournamentTabs'
  | 'Tournaments'
  | 'UserPredictionGroups'
  | 'UserPredictions'
  | '_pageData'

type FieldMap = typeof fieldMap
export const fieldMap = {
  Alphabets: [
    'Alphabets.Alphabet',
    'Alphabets.IsTransliterated',
    'Alphabets._pageName',
    'Alphabets._pageTitle',
    'Alphabets._pageNamespace',
    'Alphabets._pageID',
    'Alphabets._ID',
  ],
  BroadcastMusicTrackTypes: [
    'BroadcastMusicTrackTypes.Type',
    'BroadcastMusicTrackTypes.Priority',
    'BroadcastMusicTrackTypes._pageName',
    'BroadcastMusicTrackTypes._pageTitle',
    'BroadcastMusicTrackTypes._pageNamespace',
    'BroadcastMusicTrackTypes._pageID',
    'BroadcastMusicTrackTypes._ID',
  ],
  BroadcastMusicTracks: [
    'BroadcastMusicTracks.TrackID',
    'BroadcastMusicTracks.TrackName',
    'BroadcastMusicTracks.Album',
    'BroadcastMusicTracks.Publishers',
    'BroadcastMusicTracks.Label',
    'BroadcastMusicTracks.TrackLength',
    'BroadcastMusicTracks.Artists',
    'BroadcastMusicTracks._pageName',
    'BroadcastMusicTracks._pageTitle',
    'BroadcastMusicTracks._pageNamespace',
    'BroadcastMusicTracks._pageID',
    'BroadcastMusicTracks._ID',
  ],
  BroadcastMusicUsages: [
    'BroadcastMusicUsages.TrackID',
    'BroadcastMusicUsages.Tournament',
    'BroadcastMusicUsages.Type',
    'BroadcastMusicUsages.Link',
    'BroadcastMusicUsages.LinkType',
    'BroadcastMusicUsages._pageName',
    'BroadcastMusicUsages._pageTitle',
    'BroadcastMusicUsages._pageNamespace',
    'BroadcastMusicUsages._pageID',
    'BroadcastMusicUsages._ID',
  ],
  CargoAttachments: [
    'CargoAttachments.CargoTable',
    'CargoAttachments.TemplateName',
    'CargoAttachments._pageName',
    'CargoAttachments._pageTitle',
    'CargoAttachments._pageNamespace',
    'CargoAttachments._pageID',
    'CargoAttachments._ID',
  ],
  ChampionFlashcards: [
    'ChampionFlashcards.Year',
    'ChampionFlashcards.Champion',
    'ChampionFlashcards.ChampionRange',
    'ChampionFlashcards.DamageType',
    'ChampionFlashcards.CCLevel',
    'ChampionFlashcards.BurstLevel',
    'ChampionFlashcards.SustainedLevel',
    'ChampionFlashcards.TankLevel',
    'ChampionFlashcards.Goal',
    'ChampionFlashcards.Strengths',
    'ChampionFlashcards.Weaknesses',
    'ChampionFlashcards.Ultimate',
    'ChampionFlashcards.Mechanic',
    'ChampionFlashcards.Classes',
    'ChampionFlashcards.Roles',
    'ChampionFlashcards._pageName',
    'ChampionFlashcards._pageTitle',
    'ChampionFlashcards._pageNamespace',
    'ChampionFlashcards._pageID',
    'ChampionFlashcards._ID',
  ],
  Champions: [
    'Champions.Name',
    'Champions.Title',
    'Champions.ReleaseDate',
    'Champions.BE',
    'Champions.RP',
    'Champions.Attributes',
    'Champions.Resource',
    'Champions.RealName',
    'Champions.Health',
    'Champions.HPLevel',
    'Champions.HPDisplay',
    'Champions.HPLevelDisplay',
    'Champions.HPRegen',
    'Champions.HPRegenLevel',
    'Champions.Mana',
    'Champions.ManaLevel',
    'Champions.ManaRegen',
    'Champions.ManaRegenLevel',
    'Champions.Energy',
    'Champions.EnergyRegen',
    'Champions.Movespeed',
    'Champions.AttackDamage',
    'Champions.ADLevel',
    'Champions.AttackSpeed',
    'Champions.ASLevel',
    'Champions.AttackRange',
    'Champions.Armor',
    'Champions.ArmorLevel',
    'Champions.MagicResist',
    'Champions.MagicResistLevel',
    'Champions.Pronoun',
    'Champions.KeyDdragon',
    'Champions.KeyInteger',
    'Champions._pageName',
    'Champions._pageTitle',
    'Champions._pageNamespace',
    'Champions._pageID',
    'Champions._ID',
  ],
  ChromaSets: [
    'ChromaSets.Champion',
    'ChromaSets.Skin',
    'ChromaSets.ReleaseDate',
    'ChromaSets.RP',
    'ChromaSets.Name',
    'ChromaSets.NumberOfChromas',
    'ChromaSets.UniqueSet',
    'ChromaSets._pageName',
    'ChromaSets._pageTitle',
    'ChromaSets._pageNamespace',
    'ChromaSets._pageID',
    'ChromaSets._ID',
  ],
  Chromas: [
    'Chromas.Name',
    'Chromas.Skin',
    'Chromas.Champion',
    'Chromas.IsBundleExclusive',
    'Chromas.IsLootExclusive',
    'Chromas.Special',
    'Chromas.ReleaseDate',
    'Chromas.BundleRP',
    'Chromas.RP',
    'Chromas.Hex1',
    'Chromas.Hex2',
    'Chromas.UniqueSet',
    'Chromas._pageName',
    'Chromas._pageTitle',
    'Chromas._pageNamespace',
    'Chromas._pageID',
    'Chromas._ID',
  ],
  Contracts: [
    'Contracts.Player',
    'Contracts.Team',
    'Contracts.ContractEnd',
    'Contracts.IsRemoval',
    'Contracts.NewsId',
    'Contracts._pageName',
    'Contracts._pageTitle',
    'Contracts._pageNamespace',
    'Contracts._pageID',
    'Contracts._ID',
  ],
  CurrentLeagues: [
    'CurrentLeagues.Event',
    'CurrentLeagues.Page',
    'CurrentLeagues.Priority',
    'CurrentLeagues._pageName',
    'CurrentLeagues._pageTitle',
    'CurrentLeagues._pageNamespace',
    'CurrentLeagues._pageID',
    'CurrentLeagues._ID',
  ],
  Disambiguations: [
    'Disambiguations.FinalLocation',
    'Disambiguations.Term',
    'Disambiguations.DisambigType',
    'Disambiguations.N_LineInPage',
    'Disambiguations.DisambigID',
    'Disambiguations._pageName',
    'Disambiguations._pageTitle',
    'Disambiguations._pageNamespace',
    'Disambiguations._pageID',
    'Disambiguations._ID',
  ],
  Entities: [
    'Entities.Entity',
    'Entities.EntityName',
    'Entities.EntityPage',
    'Entities.EntityType',
    'Entities.IsLowercase',
    'Entities.DisambigSentence',
    'Entities._pageName',
    'Entities._pageTitle',
    'Entities._pageNamespace',
    'Entities._pageID',
    'Entities._ID',
  ],
  ExternalContent: [
    'ExternalContent.Title',
    'ExternalContent.URL',
    'ExternalContent.ContentType',
    'ExternalContent.MediaType',
    'ExternalContent.Language',
    'ExternalContent.Players',
    'ExternalContent.Tournaments',
    'ExternalContent.Teams',
    'ExternalContent.Date',
    'ExternalContent.Year',
    'ExternalContent.Publication',
    'ExternalContent.N_ItemInDate',
    'ExternalContent.Authors',
    'ExternalContent.Translators',
    'ExternalContent.Series',
    'ExternalContent.SeriesSeason',
    'ExternalContent.SeriesSeasonNumber',
    'ExternalContent._pageName',
    'ExternalContent._pageTitle',
    'ExternalContent._pageNamespace',
    'ExternalContent._pageID',
    'ExternalContent._ID',
  ],
  GCDArchive: [
    'GCDArchive.Region',
    'GCDArchive.RegionAbbreviation',
    'GCDArchive.PageDate',
    'GCDArchive.PageDateTime',
    'GCDArchive.UpdateDate',
    'GCDArchive.PageURLDate',
    'GCDArchive.IsNew',
    'GCDArchive.Diff',
    'GCDArchive.Diff_URL',
    'GCDArchive._pageName',
    'GCDArchive._pageTitle',
    'GCDArchive._pageNamespace',
    'GCDArchive._pageID',
    'GCDArchive._ID',
  ],
  Hooks: [
    'Hooks.Hook',
    'Hooks.Module',
    'Hooks.Action',
    'Hooks._pageName',
    'Hooks._pageTitle',
    'Hooks._pageNamespace',
    'Hooks._pageID',
    'Hooks._ID',
  ],
  IgnorePagedata: [
    'IgnorePagedata.TypeOfIgnore',
    'IgnorePagedata._pageName',
    'IgnorePagedata._pageTitle',
    'IgnorePagedata._pageNamespace',
    'IgnorePagedata._pageID',
    'IgnorePagedata._ID',
  ],
  IndividualAchievements: [
    'IndividualAchievements.Player',
    'IndividualAchievements.Link',
    'IndividualAchievements.Team',
    'IndividualAchievements.OverviewPage',
    'IndividualAchievements.Display',
    'IndividualAchievements.Place',
    'IndividualAchievements.Place_Number',
    'IndividualAchievements.AchievementType',
    'IndividualAchievements.Description',
    'IndividualAchievements._pageName',
    'IndividualAchievements._pageTitle',
    'IndividualAchievements._pageNamespace',
    'IndividualAchievements._pageID',
    'IndividualAchievements._ID',
  ],
  Items: [
    'Items.Name',
    'Items.Recipe',
    'Items.Cost',
    'Items.TotalCost',
    'Items.AD',
    'Items.LifeSteal',
    'Items.Health',
    'Items.HPRegen',
    'Items.Armor',
    'Items.MR',
    'Items.AttackDamage',
    'Items.Crit',
    'Items.AttackSpeed',
    'Items.ArmorPen',
    'Items.AttackRange',
    'Items.Mana',
    'Items.ManaRegen',
    'Items.Energy',
    'Items.EnergyRegen',
    'Items.AP',
    'Items.CDR',
    'Items.AbilityHaste',
    'Items.Omnivamp',
    'Items.PhysVamp',
    'Items.SpellVamp',
    'Items.MPen',
    'Items.MovespeedFlat',
    'Items.MovespeedPercent',
    'Items.Tenacity',
    'Items.GoldGen',
    'Items.OnHit',
    'Items.BonusHP',
    'Items.Healing',
    'Items.HSPower',
    'Items.SlowResist',
    'Items._pageName',
    'Items._pageTitle',
    'Items._pageNamespace',
    'Items._pageID',
    'Items._ID',
  ],
  LeagueGroups: [
    'LeagueGroups.LongName',
    'LeagueGroups.ShortName',
    'LeagueGroups.Leagues',
    'LeagueGroups._pageName',
    'LeagueGroups._pageTitle',
    'LeagueGroups._pageNamespace',
    'LeagueGroups._pageID',
    'LeagueGroups._ID',
  ],
  Leagues: [
    'Leagues.League',
    'Leagues.League_Short',
    'Leagues.Region',
    'Leagues.Level',
    'Leagues.IsOfficial',
    'Leagues._pageName',
    'Leagues._pageTitle',
    'Leagues._pageNamespace',
    'Leagues._pageID',
    'Leagues._ID',
  ],
  ListplayerCurrent: [
    'ListplayerCurrent.ID',
    'ListplayerCurrent.Link',
    'ListplayerCurrent.Name',
    'ListplayerCurrent.N',
    'ListplayerCurrent.Country',
    'ListplayerCurrent.Role',
    'ListplayerCurrent.IsSubstitute',
    'ListplayerCurrent.IsTrainee',
    'ListplayerCurrent.Team',
    'ListplayerCurrent.ContractDate',
    'ListplayerCurrent.Residency',
    'ListplayerCurrent._pageName',
    'ListplayerCurrent._pageTitle',
    'ListplayerCurrent._pageNamespace',
    'ListplayerCurrent._pageID',
    'ListplayerCurrent._ID',
  ],
  LowPriorityRedirects: [
    'LowPriorityRedirects.IsLowPriority',
    'LowPriorityRedirects._pageName',
    'LowPriorityRedirects._pageTitle',
    'LowPriorityRedirects._pageNamespace',
    'LowPriorityRedirects._pageID',
    'LowPriorityRedirects._ID',
  ],
  MatchSchedule: [
    'MatchSchedule.Team1',
    'MatchSchedule.Team2',
    'MatchSchedule.Team1Final',
    'MatchSchedule.Team2Final',
    'MatchSchedule.Winner',
    'MatchSchedule.Team1Points',
    'MatchSchedule.Team2Points',
    'MatchSchedule.Team1PointsTB',
    'MatchSchedule.Team2PointsTB',
    'MatchSchedule.Team1Score',
    'MatchSchedule.Team2Score',
    'MatchSchedule.Team1Poster',
    'MatchSchedule.Team2Poster',
    'MatchSchedule.Team1Advantage',
    'MatchSchedule.Team2Advantage',
    'MatchSchedule.FF',
    'MatchSchedule.Player1',
    'MatchSchedule.Player2',
    'MatchSchedule.MatchDay',
    'MatchSchedule.DateTime_UTC',
    'MatchSchedule.HasTime',
    'MatchSchedule.DST',
    'MatchSchedule.IsFlexibleStart',
    'MatchSchedule.IsReschedulable',
    'MatchSchedule.OverrideAllowPredictions',
    'MatchSchedule.IsTiebreaker',
    'MatchSchedule.OverviewPage',
    'MatchSchedule.ShownName',
    'MatchSchedule.ShownRound',
    'MatchSchedule.BestOf',
    'MatchSchedule.Round',
    'MatchSchedule.Phase',
    'MatchSchedule.N_MatchInPage',
    'MatchSchedule.Tab',
    'MatchSchedule.N_MatchInTab',
    'MatchSchedule.N_TabInPage',
    'MatchSchedule.N_Page',
    'MatchSchedule.Patch',
    'MatchSchedule.PatchPage',
    'MatchSchedule.Hotfix',
    'MatchSchedule.DisabledChampions',
    'MatchSchedule.PatchFootnote',
    'MatchSchedule.InitialN_MatchInTab',
    'MatchSchedule.InitialPageAndTab',
    'MatchSchedule.GroupName',
    'MatchSchedule.Stream',
    'MatchSchedule.StreamDisplay',
    'MatchSchedule.Venue',
    'MatchSchedule.CastersPBP',
    'MatchSchedule.CastersColor',
    'MatchSchedule.Casters',
    'MatchSchedule.MVP',
    'MatchSchedule.MVPPoints',
    'MatchSchedule.VodInterview',
    'MatchSchedule.VodHighlights',
    'MatchSchedule.InterviewWith',
    'MatchSchedule.Recap',
    'MatchSchedule.Reddit',
    'MatchSchedule.QQ',
    'MatchSchedule.Wanplus',
    'MatchSchedule.WanplusId',
    'MatchSchedule.PageAndTeam1',
    'MatchSchedule.PageAndTeam2',
    'MatchSchedule.Team1Footnote',
    'MatchSchedule.Team2Footnote',
    'MatchSchedule.Footnote',
    'MatchSchedule.UniqueMatch',
    'MatchSchedule.MatchId',
    'MatchSchedule.UserSignup',
    'MatchSchedule.Tags',
    'MatchSchedule._pageName',
    'MatchSchedule._pageTitle',
    'MatchSchedule._pageNamespace',
    'MatchSchedule._pageID',
    'MatchSchedule._ID',
  ],
  MatchScheduleGame: [
    'MatchScheduleGame.Blue',
    'MatchScheduleGame.Red',
    'MatchScheduleGame.Winner',
    'MatchScheduleGame.BlueFinal',
    'MatchScheduleGame.RedFinal',
    'MatchScheduleGame.BlueFootnote',
    'MatchScheduleGame.RedFootnote',
    'MatchScheduleGame.Footnote',
    'MatchScheduleGame.IsChronobreak',
    'MatchScheduleGame.IsRemake',
    'MatchScheduleGame.FF',
    'MatchScheduleGame.Selection',
    'MatchScheduleGame.HasSelection',
    'MatchScheduleGame.MatchHistory',
    'MatchScheduleGame.Recap',
    'MatchScheduleGame.Reddit',
    'MatchScheduleGame.Vod',
    'MatchScheduleGame.VodPB',
    'MatchScheduleGame.VodGameStart',
    'MatchScheduleGame.VodPostgame',
    'MatchScheduleGame.VodHighlights',
    'MatchScheduleGame.VodInterview',
    'MatchScheduleGame.InterviewWith',
    'MatchScheduleGame.MVP',
    'MatchScheduleGame.MVPPoints',
    'MatchScheduleGame.OverviewPage',
    'MatchScheduleGame.N_MatchInTab',
    'MatchScheduleGame.N_TabInPage',
    'MatchScheduleGame.N_GameInMatch',
    'MatchScheduleGame.N_Page',
    'MatchScheduleGame.ScoreboardID_Wiki',
    'MatchScheduleGame.ScoreboardID_Riot',
    'MatchScheduleGame.GameID_Wiki',
    'MatchScheduleGame.GameId',
    'MatchScheduleGame.UniqueMatch',
    'MatchScheduleGame.MatchId',
    'MatchScheduleGame.UniqueLine',
    'MatchScheduleGame.WrittenSummary',
    'MatchScheduleGame._pageName',
    'MatchScheduleGame._pageTitle',
    'MatchScheduleGame._pageNamespace',
    'MatchScheduleGame._pageID',
    'MatchScheduleGame._ID',
  ],
  NASGLadder2018: [
    'NASGLadder2018.Display',
    'NASGLadder2018.Link',
    'NASGLadder2018.Year',
    'NASGLadder2018.Cycle1',
    'NASGLadder2018.Cycle2',
    'NASGLadder2018.Cycle3',
    'NASGLadder2018.Cycle4',
    'NASGLadder2018.Cycle5',
    'NASGLadder2018.Cycle6',
    'NASGLadder2018.Cycle7',
    'NASGLadder2018.Cycle8',
    'NASGLadder2018.Total',
    'NASGLadder2018.Role',
    'NASGLadder2018._pageName',
    'NASGLadder2018._pageTitle',
    'NASGLadder2018._pageNamespace',
    'NASGLadder2018._pageID',
    'NASGLadder2018._ID',
  ],
  NASGLadder7Cycles: [
    'NASGLadder7Cycles.Display',
    'NASGLadder7Cycles.Link',
    'NASGLadder7Cycles.Year',
    'NASGLadder7Cycles.Cycle1',
    'NASGLadder7Cycles.Cycle2',
    'NASGLadder7Cycles.Cycle3',
    'NASGLadder7Cycles.Cycle4',
    'NASGLadder7Cycles.Cycle5',
    'NASGLadder7Cycles.Cycle6',
    'NASGLadder7Cycles.Cycle7',
    'NASGLadder7Cycles.Total',
    'NASGLadder7Cycles.Role',
    'NASGLadder7Cycles._pageName',
    'NASGLadder7Cycles._pageTitle',
    'NASGLadder7Cycles._pageNamespace',
    'NASGLadder7Cycles._pageID',
    'NASGLadder7Cycles._ID',
  ],
  NTLGlossary: [
    'NTLGlossary.Term',
    'NTLGlossary.Term_LC',
    'NTLGlossary.Definition',
    'NTLGlossary.Categories',
    'NTLGlossary._pageName',
    'NTLGlossary._pageTitle',
    'NTLGlossary._pageNamespace',
    'NTLGlossary._pageID',
    'NTLGlossary._ID',
  ],
  NewsItems: [
    'NewsItems.Date_Display',
    'NewsItems.Date_Sort',
    'NewsItems.IsApproxDate',
    'NewsItems.EarliestPossibleDate',
    'NewsItems.LatestPossibleDate',
    'NewsItems.Sentence',
    'NewsItems.SentenceWithDate',
    'NewsItems.Sentence_Team',
    'NewsItems.Sentence_Player',
    'NewsItems.Sentence_Tournament',
    'NewsItems.Subject',
    'NewsItems.SubjectType',
    'NewsItems.SubjectLink',
    'NewsItems.Preload',
    'NewsItems.Region',
    'NewsItems.Players',
    'NewsItems.Teams',
    'NewsItems.Tournaments',
    'NewsItems.Tags',
    'NewsItems.Source',
    'NewsItems.N_LineInDate',
    'NewsItems.NewsId',
    'NewsItems.ExcludeFrontpage',
    'NewsItems.ExcludePortal',
    'NewsItems._pageName',
    'NewsItems._pageTitle',
    'NewsItems._pageNamespace',
    'NewsItems._pageID',
    'NewsItems._ID',
  ],
  Organizations: [
    'Organizations.Name',
    'Organizations.OverviewPage',
    'Organizations.Location',
    'Organizations.Region',
    'Organizations.Image',
    'Organizations.Twitter',
    'Organizations.Youtube',
    'Organizations.Facebook',
    'Organizations.Instagram',
    'Organizations.Discord',
    'Organizations.Snapchat',
    'Organizations.Vk',
    'Organizations.Subreddit',
    'Organizations.IsLowercase',
    'Organizations._pageName',
    'Organizations._pageTitle',
    'Organizations._pageNamespace',
    'Organizations._pageID',
    'Organizations._ID',
  ],
  ParticipantsArgs: [
    'ParticipantsArgs.OverviewPage',
    'ParticipantsArgs.N_TeamInPage',
    'ParticipantsArgs.Pool',
    'ParticipantsArgs.Args',
    'ParticipantsArgs._pageName',
    'ParticipantsArgs._pageTitle',
    'ParticipantsArgs._pageNamespace',
    'ParticipantsArgs._pageID',
    'ParticipantsArgs._ID',
  ],
  PatchNotes: [
    'PatchNotes.EntityType',
    'PatchNotes.Entity',
    'PatchNotes.Changes',
    'PatchNotes.Patch',
    'PatchNotes._pageName',
    'PatchNotes._pageTitle',
    'PatchNotes._pageNamespace',
    'PatchNotes._pageID',
    'PatchNotes._ID',
  ],
  Pentakills: [
    'Pentakills.N',
    'Pentakills.DateDisplay',
    'Pentakills.DateSort',
    'Pentakills.Region',
    'Pentakills.Tournament',
    'Pentakills.OverviewPage',
    'Pentakills.Team',
    'Pentakills.TeamVs',
    'Pentakills.Name',
    'Pentakills.Link',
    'Pentakills.Champion',
    'Pentakills.Role',
    'Pentakills.Win',
    'Pentakills.Kills',
    'Pentakills.Deaths',
    'Pentakills.Assists',
    'Pentakills.ScoreboardLink',
    'Pentakills.Vod',
    'Pentakills._pageName',
    'Pentakills._pageTitle',
    'Pentakills._pageNamespace',
    'Pentakills._pageID',
    'Pentakills._ID',
  ],
  PicksAndBansS7: [
    'PicksAndBansS7.Team1Role1',
    'PicksAndBansS7.Team1Role2',
    'PicksAndBansS7.Team1Role3',
    'PicksAndBansS7.Team1Role4',
    'PicksAndBansS7.Team1Role5',
    'PicksAndBansS7.Team2Role1',
    'PicksAndBansS7.Team2Role2',
    'PicksAndBansS7.Team2Role3',
    'PicksAndBansS7.Team2Role4',
    'PicksAndBansS7.Team2Role5',
    'PicksAndBansS7.Team1Ban1',
    'PicksAndBansS7.Team1Ban2',
    'PicksAndBansS7.Team1Ban3',
    'PicksAndBansS7.Team1Ban4',
    'PicksAndBansS7.Team1Ban5',
    'PicksAndBansS7.Team1Pick1',
    'PicksAndBansS7.Team1Pick2',
    'PicksAndBansS7.Team1Pick3',
    'PicksAndBansS7.Team1Pick4',
    'PicksAndBansS7.Team1Pick5',
    'PicksAndBansS7.Team2Ban1',
    'PicksAndBansS7.Team2Ban2',
    'PicksAndBansS7.Team2Ban3',
    'PicksAndBansS7.Team2Ban4',
    'PicksAndBansS7.Team2Ban5',
    'PicksAndBansS7.Team2Pick1',
    'PicksAndBansS7.Team2Pick2',
    'PicksAndBansS7.Team2Pick3',
    'PicksAndBansS7.Team2Pick4',
    'PicksAndBansS7.Team2Pick5',
    'PicksAndBansS7.Team1',
    'PicksAndBansS7.Team2',
    'PicksAndBansS7.Winner',
    'PicksAndBansS7.Team1Score',
    'PicksAndBansS7.Team2Score',
    'PicksAndBansS7.Team1PicksByRoleOrder',
    'PicksAndBansS7.Team2PicksByRoleOrder',
    'PicksAndBansS7.OverviewPage',
    'PicksAndBansS7.Phase',
    'PicksAndBansS7.UniqueLine',
    'PicksAndBansS7.IsComplete',
    'PicksAndBansS7.Tab',
    'PicksAndBansS7.N_Page',
    'PicksAndBansS7.N_TabInPage',
    'PicksAndBansS7.N_MatchInPage',
    'PicksAndBansS7.N_GameInPage',
    'PicksAndBansS7.N_GameInMatch',
    'PicksAndBansS7.N_MatchInTab',
    'PicksAndBansS7.N_GameInTab',
    'PicksAndBansS7.GameId',
    'PicksAndBansS7.MatchId',
    'PicksAndBansS7.GameID_Wiki',
    'PicksAndBansS7._pageName',
    'PicksAndBansS7._pageTitle',
    'PicksAndBansS7._pageNamespace',
    'PicksAndBansS7._pageID',
    'PicksAndBansS7._ID',
  ],
  PlayerImages: [
    'PlayerImages.FileName',
    'PlayerImages.Link',
    'PlayerImages.Team',
    'PlayerImages.Tournament',
    'PlayerImages.ImageType',
    'PlayerImages.Caption',
    'PlayerImages.IsProfileImage',
    'PlayerImages.SortDate',
    'PlayerImages._pageName',
    'PlayerImages._pageTitle',
    'PlayerImages._pageNamespace',
    'PlayerImages._pageID',
    'PlayerImages._ID',
  ],
  PlayerLeagueHistory: [
    'PlayerLeagueHistory.Player',
    'PlayerLeagueHistory.Teams',
    'PlayerLeagueHistory.League',
    'PlayerLeagueHistory.LeagueHistory',
    'PlayerLeagueHistory.TotalGames',
    'PlayerLeagueHistory._pageName',
    'PlayerLeagueHistory._pageTitle',
    'PlayerLeagueHistory._pageNamespace',
    'PlayerLeagueHistory._pageID',
    'PlayerLeagueHistory._ID',
  ],
  PlayerPronunciationFiles: [
    'PlayerPronunciationFiles.Player',
    'PlayerPronunciationFiles.Name',
    'PlayerPronunciationFiles.RecordedBy',
    'PlayerPronunciationFiles.RecordedBy_User',
    'PlayerPronunciationFiles.Source',
    'PlayerPronunciationFiles.Date',
    'PlayerPronunciationFiles.Language',
    'PlayerPronunciationFiles._pageName',
    'PlayerPronunciationFiles._pageTitle',
    'PlayerPronunciationFiles._pageNamespace',
    'PlayerPronunciationFiles._pageID',
    'PlayerPronunciationFiles._ID',
  ],
  PlayerRedirects: [
    'PlayerRedirects.AllName',
    'PlayerRedirects.OverviewPage',
    'PlayerRedirects.ID',
    'PlayerRedirects._pageName',
    'PlayerRedirects._pageTitle',
    'PlayerRedirects._pageNamespace',
    'PlayerRedirects._pageID',
    'PlayerRedirects._ID',
  ],
  PlayerRenames: [
    'PlayerRenames.Date',
    'PlayerRenames.OriginalName',
    'PlayerRenames.NewName',
    'PlayerRenames.NewsId',
    'PlayerRenames.IsRestyle',
    'PlayerRenames._pageName',
    'PlayerRenames._pageTitle',
    'PlayerRenames._pageNamespace',
    'PlayerRenames._pageID',
    'PlayerRenames._ID',
  ],
  Players: [
    'Players.ID',
    'Players.OverviewPage',
    'Players.Player',
    'Players.Image',
    'Players.Name',
    'Players.NativeName',
    'Players.NameAlphabet',
    'Players.NameFull',
    'Players.Country',
    'Players.Nationality',
    'Players.NationalityPrimary',
    'Players.Age',
    'Players.Birthdate',
    'Players.ResidencyFormer',
    'Players.Team',
    'Players.Team2',
    'Players.CurrentTeams',
    'Players.TeamSystem',
    'Players.Team2System',
    'Players.Residency',
    'Players.Role',
    'Players.FavChamps',
    'Players.SoloqueueIds',
    'Players.Askfm',
    'Players.Discord',
    'Players.Facebook',
    'Players.Instagram',
    'Players.Lolpros',
    'Players.Reddit',
    'Players.Snapchat',
    'Players.Stream',
    'Players.Twitter',
    'Players.Vk',
    'Players.Website',
    'Players.Weibo',
    'Players.Youtube',
    'Players.TeamLast',
    'Players.RoleLast',
    'Players.IsRetired',
    'Players.ToWildrift',
    'Players.IsPersonality',
    'Players.IsSubstitute',
    'Players.IsTrainee',
    'Players.IsLowercase',
    'Players.IsAutoTeam',
    'Players.IsLowContent',
    'Players._pageName',
    'Players._pageTitle',
    'Players._pageNamespace',
    'Players._pageID',
    'Players._ID',
  ],
  RegionStatuses: [
    'RegionStatuses.Region',
    'RegionStatuses.Year',
    'RegionStatuses.Status',
    'RegionStatuses._pageName',
    'RegionStatuses._pageTitle',
    'RegionStatuses._pageNamespace',
    'RegionStatuses._pageID',
    'RegionStatuses._ID',
  ],
  Regions: [
    'Regions.RegionLong',
    'Regions.RegionMedium',
    'Regions.Priority',
    'Regions.IsCurrent',
    'Regions._pageName',
    'Regions._pageTitle',
    'Regions._pageNamespace',
    'Regions._pageID',
    'Regions._ID',
  ],
  ResidencyChanges: [
    'ResidencyChanges.Player',
    'ResidencyChanges.NewsId',
    'ResidencyChanges.ResidencyOld',
    'ResidencyChanges.ResidencyNew',
    'ResidencyChanges._pageName',
    'ResidencyChanges._pageTitle',
    'ResidencyChanges._pageNamespace',
    'ResidencyChanges._pageID',
    'ResidencyChanges._ID',
  ],
  Retirements: [
    'Retirements.Player',
    'Retirements.NewsId',
    'Retirements.Unretires',
    'Retirements._pageName',
    'Retirements._pageTitle',
    'Retirements._pageNamespace',
    'Retirements._pageID',
    'Retirements._ID',
  ],
  RosterChangePortalDates: [
    'RosterChangePortalDates.Region',
    'RosterChangePortalDates.DateStart',
    'RosterChangePortalDates.DateEnd',
    'RosterChangePortalDates.Year',
    'RosterChangePortalDates.Period',
    'RosterChangePortalDates.PeriodName',
    'RosterChangePortalDates.PeriodSort',
    'RosterChangePortalDates.OverviewPage',
    'RosterChangePortalDates._pageName',
    'RosterChangePortalDates._pageTitle',
    'RosterChangePortalDates._pageNamespace',
    'RosterChangePortalDates._pageID',
    'RosterChangePortalDates._ID',
  ],
  RosterChangePortalPages: [
    'RosterChangePortalPages.SplitOrder',
    'RosterChangePortalPages.Year',
    'RosterChangePortalPages._pageName',
    'RosterChangePortalPages._pageTitle',
    'RosterChangePortalPages._pageNamespace',
    'RosterChangePortalPages._pageID',
    'RosterChangePortalPages._ID',
  ],
  RosterChanges: [
    'RosterChanges.Date_Sort',
    'RosterChanges.Player',
    'RosterChanges.Direction',
    'RosterChanges.Team',
    'RosterChanges.RolesIngame',
    'RosterChanges.RolesStaff',
    'RosterChanges.Roles',
    'RosterChanges.RoleDisplay',
    'RosterChanges.Role',
    'RosterChanges.RoleModifier',
    'RosterChanges.Status',
    'RosterChanges.CurrentTeamPriority',
    'RosterChanges.PlayerUnlinked',
    'RosterChanges.AlreadyJoined',
    'RosterChanges.Tournaments',
    'RosterChanges.Source',
    'RosterChanges.IsGCD',
    'RosterChanges.Preload',
    'RosterChanges.PreloadSortNumber',
    'RosterChanges.Tags',
    'RosterChanges.NewsId',
    'RosterChanges.RosterChangeId',
    'RosterChanges.N_LineInNews',
    'RosterChanges._pageName',
    'RosterChanges._pageTitle',
    'RosterChanges._pageNamespace',
    'RosterChanges._pageID',
    'RosterChanges._ID',
  ],
  RosterRumors: [
    'RosterRumors.Date',
    'RosterRumors.Status',
    'RosterRumors.IsOver',
    'RosterRumors.NotHappening',
    'RosterRumors.Player',
    'RosterRumors.Regions',
    'RosterRumors.TeamStart',
    'RosterRumors.TeamEnd',
    'RosterRumors.LeagueStart',
    'RosterRumors.LeagueEnd',
    'RosterRumors.RegionStart',
    'RosterRumors.RegionEnd',
    'RosterRumors.RoleStart',
    'RosterRumors.RoleEnd',
    'RosterRumors.IsSubStart',
    'RosterRumors.IsSubEnd',
    'RosterRumors.IsTraineeStart',
    'RosterRumors.IsTraineeEnd',
    'RosterRumors.CustomText',
    'RosterRumors.SourceLink',
    'RosterRumors.SourceAuthors',
    'RosterRumors.SourceSite',
    'RosterRumors.StatusLink',
    'RosterRumors.N_LineInDate',
    'RosterRumors._pageName',
    'RosterRumors._pageTitle',
    'RosterRumors._pageNamespace',
    'RosterRumors._pageID',
    'RosterRumors._ID',
  ],
  ScoreboardGames: [
    'ScoreboardGames.OverviewPage',
    'ScoreboardGames.Tournament',
    'ScoreboardGames.Team1',
    'ScoreboardGames.Team2',
    'ScoreboardGames.WinTeam',
    'ScoreboardGames.LossTeam',
    'ScoreboardGames.DateTime_UTC',
    'ScoreboardGames.DST',
    'ScoreboardGames.Team1Score',
    'ScoreboardGames.Team2Score',
    'ScoreboardGames.Winner',
    'ScoreboardGames.Gamelength',
    'ScoreboardGames.Gamelength_Number',
    'ScoreboardGames.Team1Bans',
    'ScoreboardGames.Team2Bans',
    'ScoreboardGames.Team1Picks',
    'ScoreboardGames.Team2Picks',
    'ScoreboardGames.Team1Players',
    'ScoreboardGames.Team2Players',
    'ScoreboardGames.Team1Dragons',
    'ScoreboardGames.Team2Dragons',
    'ScoreboardGames.Team1Barons',
    'ScoreboardGames.Team2Barons',
    'ScoreboardGames.Team1Towers',
    'ScoreboardGames.Team2Towers',
    'ScoreboardGames.Team1Gold',
    'ScoreboardGames.Team2Gold',
    'ScoreboardGames.Team1Kills',
    'ScoreboardGames.Team2Kills',
    'ScoreboardGames.Team1RiftHeralds',
    'ScoreboardGames.Team2RiftHeralds',
    'ScoreboardGames.Team1Inhibitors',
    'ScoreboardGames.Team2Inhibitors',
    'ScoreboardGames.Patch',
    'ScoreboardGames.PatchSort',
    'ScoreboardGames.MatchHistory',
    'ScoreboardGames.VOD',
    'ScoreboardGames.N_Page',
    'ScoreboardGames.N_MatchInTab',
    'ScoreboardGames.N_MatchInPage',
    'ScoreboardGames.N_GameInMatch',
    'ScoreboardGames.Gamename',
    'ScoreboardGames.UniqueGame',
    'ScoreboardGames.UniqueLine',
    'ScoreboardGames.GameId',
    'ScoreboardGames.MatchId',
    'ScoreboardGames.ScoreboardID_Wiki',
    'ScoreboardGames.ScoreboardID_Riot',
    'ScoreboardGames.Note1',
    'ScoreboardGames.Note2',
    'ScoreboardGames.Note3',
    'ScoreboardGames.Note4',
    'ScoreboardGames._pageName',
    'ScoreboardGames._pageTitle',
    'ScoreboardGames._pageNamespace',
    'ScoreboardGames._pageID',
    'ScoreboardGames._ID',
  ],
  ScoreboardPlayers: [
    'ScoreboardPlayers.OverviewPage',
    'ScoreboardPlayers.Name',
    'ScoreboardPlayers.Link',
    'ScoreboardPlayers.Champion',
    'ScoreboardPlayers.Kills',
    'ScoreboardPlayers.Deaths',
    'ScoreboardPlayers.Assists',
    'ScoreboardPlayers.SummonerSpells',
    'ScoreboardPlayers.Gold',
    'ScoreboardPlayers.CS',
    'ScoreboardPlayers.Items',
    'ScoreboardPlayers.Trinket',
    'ScoreboardPlayers.KeystoneMastery',
    'ScoreboardPlayers.KeystoneRune',
    'ScoreboardPlayers.PrimaryTree',
    'ScoreboardPlayers.SecondaryTree',
    'ScoreboardPlayers.Runes',
    'ScoreboardPlayers.TeamKills',
    'ScoreboardPlayers.TeamGold',
    'ScoreboardPlayers.Team',
    'ScoreboardPlayers.TeamVs',
    'ScoreboardPlayers.Time',
    'ScoreboardPlayers.PlayerWin',
    'ScoreboardPlayers.DateTime_UTC',
    'ScoreboardPlayers.DST',
    'ScoreboardPlayers.Tournament',
    'ScoreboardPlayers.Role',
    'ScoreboardPlayers.Role_Number',
    'ScoreboardPlayers.IngameRole',
    'ScoreboardPlayers.Side',
    'ScoreboardPlayers.GameIDWiki',
    'ScoreboardPlayers.GameIDRiot',
    'ScoreboardPlayers.UniqueGame',
    'ScoreboardPlayers.UniqueLine',
    'ScoreboardPlayers.UniqueLineVs',
    'ScoreboardPlayers.UniqueRole',
    'ScoreboardPlayers.UniqueRoleVs',
    'ScoreboardPlayers.GameId',
    'ScoreboardPlayers.MatchId',
    'ScoreboardPlayers.GameTeamId',
    'ScoreboardPlayers.GameRoleId',
    'ScoreboardPlayers.GameRoleIdVs',
    'ScoreboardPlayers.StatsPage',
    'ScoreboardPlayers._pageName',
    'ScoreboardPlayers._pageTitle',
    'ScoreboardPlayers._pageNamespace',
    'ScoreboardPlayers._pageID',
    'ScoreboardPlayers._ID',
  ],
  ScoreboardTeams: [
    'ScoreboardTeams.Team',
    'ScoreboardTeams.Side',
    'ScoreboardTeams.Number',
    'ScoreboardTeams.IsWinner',
    'ScoreboardTeams.Score',
    'ScoreboardTeams.Bans',
    'ScoreboardTeams.Picks',
    'ScoreboardTeams.Roster',
    'ScoreboardTeams.Dragons',
    'ScoreboardTeams.Barons',
    'ScoreboardTeams.Towers',
    'ScoreboardTeams.Gold',
    'ScoreboardTeams.Kills',
    'ScoreboardTeams.RiftHeralds',
    'ScoreboardTeams.Inhibitors',
    'ScoreboardTeams.OverviewPage',
    'ScoreboardTeams.StatsPage',
    'ScoreboardTeams.UniqueGame',
    'ScoreboardTeams.UniqueTeam',
    'ScoreboardTeams.GameId',
    'ScoreboardTeams.MatchId',
    'ScoreboardTeams.GameTeamId',
    'ScoreboardTeams._pageName',
    'ScoreboardTeams._pageTitle',
    'ScoreboardTeams._pageNamespace',
    'ScoreboardTeams._pageID',
    'ScoreboardTeams._ID',
  ],
  SisterTeams: [
    'SisterTeams.Team',
    'SisterTeams.Team_Markup',
    'SisterTeams.Status',
    'SisterTeams.ActiveList',
    'SisterTeams.InactiveList',
    'SisterTeams.Active_Markup',
    'SisterTeams.Inactive_Markup',
    'SisterTeams.AllTeams',
    'SisterTeams.AllTeams_Markup',
    'SisterTeams._pageName',
    'SisterTeams._pageTitle',
    'SisterTeams._pageNamespace',
    'SisterTeams._pageID',
    'SisterTeams._ID',
  ],
  Skins: [
    'Skins.Name',
    'Skins.Champion',
    'Skins.RP',
    'Skins.ReleaseDate',
    'Skins.Artists',
    'Skins.IsLegacy',
    'Skins.Special',
    'Skins.HasChromas',
    'Skins.IsClassic',
    'Skins.IsReleased',
    'Skins._pageName',
    'Skins._pageTitle',
    'Skins._pageNamespace',
    'Skins._pageID',
    'Skins._ID',
  ],
  SkinsUsed: [
    'SkinsUsed.Champion',
    'SkinsUsed.Skin',
    'SkinsUsed.Chroma',
    'SkinsUsed.OverviewPage',
    'SkinsUsed._pageName',
    'SkinsUsed._pageTitle',
    'SkinsUsed._pageNamespace',
    'SkinsUsed._pageID',
    'SkinsUsed._ID',
  ],
  Standings: [
    'Standings.OverviewPage',
    'Standings.Team',
    'Standings.PageAndTeam',
    'Standings.N',
    'Standings.Place',
    'Standings.WinSeries',
    'Standings.LossSeries',
    'Standings.TieSeries',
    'Standings.WinGames',
    'Standings.LossGames',
    'Standings.Points',
    'Standings.PointsTiebreaker',
    'Standings.Streak',
    'Standings.StreakDirection',
    'Standings._pageName',
    'Standings._pageTitle',
    'Standings._pageNamespace',
    'Standings._pageID',
    'Standings._ID',
  ],
  StandingsArgs: [
    'StandingsArgs.OverviewPage',
    'StandingsArgs.TournamentGroup',
    'StandingsArgs.N',
    'StandingsArgs.Args',
    'StandingsArgs.RowArgs',
    'StandingsArgs.Finalorder',
    'StandingsArgs.UniqueLine',
    'StandingsArgs.IsOver',
    'StandingsArgs._pageName',
    'StandingsArgs._pageTitle',
    'StandingsArgs._pageNamespace',
    'StandingsArgs._pageID',
    'StandingsArgs._ID',
  ],
  TeamRedirects: [
    'TeamRedirects.AllName',
    'TeamRedirects.OtherName',
    'TeamRedirects.UniqueLine',
    'TeamRedirects._pageName',
    'TeamRedirects._pageTitle',
    'TeamRedirects._pageNamespace',
    'TeamRedirects._pageID',
    'TeamRedirects._ID',
  ],
  TeamRenames: [
    'TeamRenames.Date',
    'TeamRenames.OriginalName',
    'TeamRenames.NewName',
    'TeamRenames.Verb',
    'TeamRenames.Slot',
    'TeamRenames.IsSamePage',
    'TeamRenames.NewsId',
    'TeamRenames._pageName',
    'TeamRenames._pageTitle',
    'TeamRenames._pageNamespace',
    'TeamRenames._pageID',
    'TeamRenames._ID',
  ],
  TeamRosterPhotos: [
    'TeamRosterPhotos.FileName',
    'TeamRosterPhotos.Team',
    'TeamRosterPhotos.Tournament',
    'TeamRosterPhotos.Caption',
    'TeamRosterPhotos.SortDate',
    'TeamRosterPhotos._pageName',
    'TeamRosterPhotos._pageTitle',
    'TeamRosterPhotos._pageNamespace',
    'TeamRosterPhotos._pageID',
    'TeamRosterPhotos._ID',
  ],
  Teams: [
    'Teams.Name',
    'Teams.OverviewPage',
    'Teams.Short',
    'Teams.Location',
    'Teams.TeamLocation',
    'Teams.Region',
    'Teams.OrganizationPage',
    'Teams.Image',
    'Teams.Twitter',
    'Teams.Youtube',
    'Teams.Facebook',
    'Teams.Instagram',
    'Teams.Discord',
    'Teams.Snapchat',
    'Teams.Vk',
    'Teams.Subreddit',
    'Teams.Website',
    'Teams.RosterPhoto',
    'Teams.IsDisbanded',
    'Teams.RenamedTo',
    'Teams.IsLowercase',
    'Teams._pageName',
    'Teams._pageTitle',
    'Teams._pageNamespace',
    'Teams._pageID',
    'Teams._ID',
  ],
  TeamsWithAutoRosters: [
    'TeamsWithAutoRosters.OverviewPage',
    'TeamsWithAutoRosters._pageName',
    'TeamsWithAutoRosters._pageTitle',
    'TeamsWithAutoRosters._pageNamespace',
    'TeamsWithAutoRosters._pageID',
    'TeamsWithAutoRosters._ID',
  ],
  Tenures: [
    'Tenures.Player',
    'Tenures.Team',
    'Tenures.DateJoin',
    'Tenures.DateLeave',
    'Tenures.Duration',
    'Tenures.ContractEnd',
    'Tenures.RosterChangeIdJoin',
    'Tenures.RosterChangeIdLeave',
    'Tenures.ResidencyLeave',
    'Tenures.NameLeave',
    'Tenures.NextTeam',
    'Tenures.NextIsRetired',
    'Tenures.NextIsWildrift',
    'Tenures.IsCurrent',
    'Tenures._pageName',
    'Tenures._pageTitle',
    'Tenures._pageNamespace',
    'Tenures._pageID',
    'Tenures._ID',
  ],
  TenuresUnbroken: [
    'TenuresUnbroken.Player',
    'TenuresUnbroken.Team',
    'TenuresUnbroken.DateJoin',
    'TenuresUnbroken.DateLeave',
    'TenuresUnbroken.Duration',
    'TenuresUnbroken.ContractEnd',
    'TenuresUnbroken.RosterChangeIdJoin',
    'TenuresUnbroken.RosterChangeIdLeave',
    'TenuresUnbroken.RosterChangeIds',
    'TenuresUnbroken.ResidencyLeave',
    'TenuresUnbroken.NameLeave',
    'TenuresUnbroken.NextTeam',
    'TenuresUnbroken.NextIsRetired',
    'TenuresUnbroken.NextIsWildrift',
    'TenuresUnbroken.IsCurrent',
    'TenuresUnbroken._pageName',
    'TenuresUnbroken._pageTitle',
    'TenuresUnbroken._pageNamespace',
    'TenuresUnbroken._pageID',
    'TenuresUnbroken._ID',
  ],
  TournamentGroups: [
    'TournamentGroups.Team',
    'TournamentGroups.OverviewPage',
    'TournamentGroups.GroupName',
    'TournamentGroups.GroupDisplay',
    'TournamentGroups.GroupN',
    'TournamentGroups.PageAndTeam',
    'TournamentGroups._pageName',
    'TournamentGroups._pageTitle',
    'TournamentGroups._pageNamespace',
    'TournamentGroups._pageID',
    'TournamentGroups._ID',
  ],
  TournamentPlayers: [
    'TournamentPlayers.Team',
    'TournamentPlayers.N_PlayerInTeam',
    'TournamentPlayers.TeamOrder',
    'TournamentPlayers.Link',
    'TournamentPlayers.Player',
    'TournamentPlayers.Role',
    'TournamentPlayers.Flag',
    'TournamentPlayers.Footnote',
    'TournamentPlayers.OverviewPage',
    'TournamentPlayers.PageAndTeam',
    'TournamentPlayers.IsDistribution',
    'TournamentPlayers._pageName',
    'TournamentPlayers._pageTitle',
    'TournamentPlayers._pageNamespace',
    'TournamentPlayers._pageID',
    'TournamentPlayers._ID',
  ],
  TournamentResults: [
    'TournamentResults.Event',
    'TournamentResults.Tier',
    'TournamentResults.Date',
    'TournamentResults.RosterPage',
    'TournamentResults.Place',
    'TournamentResults.ForceNewPlace',
    'TournamentResults.Place_Number',
    'TournamentResults.Qualified',
    'TournamentResults.Prize',
    'TournamentResults.Prize_USD',
    'TournamentResults.Prize_Euro',
    'TournamentResults.PrizeUnit',
    'TournamentResults.Prize_Markup',
    'TournamentResults.PrizeOther',
    'TournamentResults.Phase',
    'TournamentResults.Team',
    'TournamentResults.IsAchievement',
    'TournamentResults.LastResult',
    'TournamentResults.LastTeam',
    'TournamentResults.LastOpponent_Markup',
    'TournamentResults.GroupName',
    'TournamentResults.LastOutcome',
    'TournamentResults.PageAndTeam',
    'TournamentResults.OverviewPage',
    'TournamentResults.UniqueLine',
    'TournamentResults._pageName',
    'TournamentResults._pageTitle',
    'TournamentResults._pageNamespace',
    'TournamentResults._pageID',
    'TournamentResults._ID',
  ],
  TournamentResults1v1: [
    'TournamentResults1v1.Event',
    'TournamentResults1v1.Tier',
    'TournamentResults1v1.Date',
    'TournamentResults1v1.Place',
    'TournamentResults1v1.Prize',
    'TournamentResults1v1.Prize_USD',
    'TournamentResults1v1.Prize_Euro',
    'TournamentResults1v1.PrizeUnit',
    'TournamentResults1v1.Prize_Markup',
    'TournamentResults1v1.PrizeOther',
    'TournamentResults1v1.Phase',
    'TournamentResults1v1.Player',
    'TournamentResults1v1.PlayerLink',
    'TournamentResults1v1.Team',
    'TournamentResults1v1.LastResult',
    'TournamentResults1v1.LastOpponent',
    'TournamentResults1v1.LastOpponentLink',
    'TournamentResults1v1.LastOutcome',
    'TournamentResults1v1.LastOpponentTeam',
    'TournamentResults1v1.OverviewPage',
    'TournamentResults1v1.UniqueLine',
    'TournamentResults1v1._pageName',
    'TournamentResults1v1._pageTitle',
    'TournamentResults1v1._pageNamespace',
    'TournamentResults1v1._pageID',
    'TournamentResults1v1._ID',
  ],
  TournamentRosters: [
    'TournamentRosters.Team',
    'TournamentRosters.OverviewPage',
    'TournamentRosters.Region',
    'TournamentRosters.RosterLinks',
    'TournamentRosters.Roles',
    'TournamentRosters.Flags',
    'TournamentRosters.Footnotes',
    'TournamentRosters.IsUsed',
    'TournamentRosters.Tournament',
    'TournamentRosters.Short',
    'TournamentRosters.IsComplete',
    'TournamentRosters.PageAndTeam',
    'TournamentRosters.UniqueLine',
    'TournamentRosters._pageName',
    'TournamentRosters._pageTitle',
    'TournamentRosters._pageNamespace',
    'TournamentRosters._pageID',
    'TournamentRosters._ID',
  ],
  TournamentTabs: [
    'TournamentTabs.BasePage',
    'TournamentTabs.BasePageDisplay',
    'TournamentTabs.Events',
    'TournamentTabs._pageName',
    'TournamentTabs._pageTitle',
    'TournamentTabs._pageNamespace',
    'TournamentTabs._pageID',
    'TournamentTabs._ID',
  ],
  Tournaments: [
    'Tournaments.Name',
    'Tournaments.OverviewPage',
    'Tournaments.DateStart',
    'Tournaments.Date',
    'Tournaments.DateStartFuzzy',
    'Tournaments.League',
    'Tournaments.Region',
    'Tournaments.Prizepool',
    'Tournaments.Currency',
    'Tournaments.Country',
    'Tournaments.ClosestTimezone',
    'Tournaments.Rulebook',
    'Tournaments.EventType',
    'Tournaments.Links',
    'Tournaments.Sponsors',
    'Tournaments.Organizer',
    'Tournaments.Organizers',
    'Tournaments.StandardName',
    'Tournaments.StandardName_Redirect',
    'Tournaments.Split',
    'Tournaments.SplitNumber',
    'Tournaments.TournamentLevel',
    'Tournaments.IsQualifier',
    'Tournaments.IsPlayoffs',
    'Tournaments.IsOfficial',
    'Tournaments.Year',
    'Tournaments.LeagueIconKey',
    'Tournaments.AlternativeNames',
    'Tournaments.ScrapeLink',
    'Tournaments.Tags',
    'Tournaments.SuppressTopSchedule',
    'Tournaments._pageName',
    'Tournaments._pageTitle',
    'Tournaments._pageNamespace',
    'Tournaments._pageID',
    'Tournaments._ID',
  ],
  UserPredictionGroups: [
    'UserPredictionGroups.GroupName',
    'UserPredictionGroups.Members',
    'UserPredictionGroups.NumberOfMembers',
    'UserPredictionGroups.OverviewPage',
    'UserPredictionGroups._pageName',
    'UserPredictionGroups._pageTitle',
    'UserPredictionGroups._pageNamespace',
    'UserPredictionGroups._pageID',
    'UserPredictionGroups._ID',
  ],
  UserPredictions: [
    'UserPredictions.User',
    'UserPredictions.OverviewPage',
    'UserPredictions.NumberOfPredictions',
    'UserPredictions.NumberCorrect',
    'UserPredictions.NumberOver',
    'UserPredictions.NumberMadeAndOver',
    'UserPredictions.PredictionList',
    'UserPredictions.PredictionOrder',
    'UserPredictions._pageName',
    'UserPredictions._pageTitle',
    'UserPredictions._pageNamespace',
    'UserPredictions._pageID',
    'UserPredictions._ID',
  ],
  _pageData: [
    '_pageData._creationDate',
    '_pageData._modificationDate',
    '_pageData._creator',
    '_pageData._categories',
    '_pageData._numRevisions',
    '_pageData._isRedirect',
    '_pageData._pageNameOrRedirect',
    '_pageData._pageName',
    '_pageData._pageTitle',
    '_pageData._pageNamespace',
    '_pageData._pageID',
    '_pageData._ID',
  ],
} as const
